### ISSUE TITLE
HEX sticker for BioCAsia2022

### ISSUE THREAD

**Issue by kozo2** [Bioconductor/BioCAsia2022#1]
Hi @kzeglinski, I'm Kozo.
I'm one of the last year's BioCAsia organizers.
@LiNk-NY and I designed the last year's sticker.
If you like, I would like to ask you for this year's sticker design.
If you don't mind, let's discuss the design here.

**Comment by PeteHaitch** [comment]
Ping @kzeglinski

**Comment by kozo2** [comment]
(This is just a thought...)
Some of the iconic buildings or landscape around the venue might be a good fit for the sticker design.

**Comment by kozo2** [comment]
https://github.com/Bioconductor/BiocStickers/tree/master/events/BiocAsia2021 is the last year's sticker[s].

The sticker above uses a copy of a copyright-free Japanese woodblock prints for the design.
Last year's BioCAsia was led by Japan, so I designed it that way.

**Comment by kzeglinski** [comment]
Hi Kozo! So sorry I didn't notice your earlier message. 
Using some iconic buildings sounds like a great idea! Maybe the [Flinders St Station](https://www.google.com/search?q=flinders+st+station&rlz=1C5GCEM_enAU915AU916&sxsrf=ALiCzsbyj7RaG7qGWd5fbBUfQnzGSl5o8Q:1660706646032&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjoz9mt9sz5AhVE-DgGHe3QB6cQ_AUoAnoECAIQBA&biw=1309&bih=1097&dpr=1.1) would be good? If you think it's ok I will make a draft this week :)

**Comment by kozo2** [comment]
Hi @kzeglinski 
It's me who should be apologizing.
I updated the first comment on this issue after Peter's comment so no wonder you didn't notice.
Flinders St Station looks cool!
I would like to ask you to make a sticker with the station.

**Comment by kzeglinski** [comment]
Hi @kozo2, sorry it took me a little longer than I'd hoped to finish. Let me know what you think! :)

![Screen Shot 2022-08-22 at 5 11 39 pm](https://user-images.githubusercontent.com/49138438/185860719-72331bf7-eb4f-4370-992d-bf3db8527ea1.png)

**Comment by kozo2** [comment]
@kzeglinski That’s great!
I will put your sticker on [the website](https://bioconductor.github.io/BioCAsia2022/) as soon as possible.
I will comment to you again as soon as it is done.

**Comment by kzeglinski** [comment]
Thanks @kozo2 ! I've attached a zip file with the original illustrator file, an .svg file and a few different sized .png files of the sticker. Let me know if you need anything else! :)
[biocasia2022.zip](https://github.com/Bioconductor/BioCAsia2022/files/9398889/biocasia2022.zip)

**Comment by kozo2** [comment]
Thanks @kzeglinski 
I replaced the blank sticker on the [website](https://bioconductor.github.io/BioCAsia2022/) with your sticker!
I uploaded your sticker files [here](https://github.com/Bioconductor/BioCAsia2022/tree/main/static/img/carousel) in the repository.

Can I add your name to [the Organizer Committee page](https://bioconductor.github.io/BioCAsia2022/organizers/)?
If it’s okay (with you), can you tell me your full name?

**Comment by kzeglinski** [comment]
Thanks @kozo2! Yes that's fine, my full name is Kathleen Zeglinski

**Comment by kozo2** [comment]
@kzeglinski 
I added you to https://bioconductor.github.io/BioCAsia2022/organizers/ .
If "the image is not yours" or "we should use another image", please let me know.

**Comment by kozo2** [comment]
@kzeglinski I would like to close this issue.
If you have any questions, feel free to contact me.
I would appreciate it if you could send a PR for your sticker to https://github.com/Bioconductor/BiocStickers/tree/master/events as well.

Thank you for your contribution!
