### ISSUE TITLE
Update 'Mark Your Calendar' dates

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BioCAsia2022#8]
I received an email from someone worried that abstracts had already closed
Could we please update these dates

![image](https://user-images.githubusercontent.com/1049741/185010532-f37ab3a9-1a60-4738-a5aa-c05d2239ad3e.png)

to something like (really just placeholders for now):

- Open now: [Registration](https://www.abacbs.org/registration#!event-register/2022/11/28/abacbs-2022) is now open
- Open now: [Call for abstracts](https://pheedloop.com/ABACBS2022/proposal/start/?call=CALGZDPQQ6NQ68Y) is now open
- Opening soon: Scholarship applications
- October 30, 2022: Call for abstracts closes
- November 14, 2022: Notification of abstract decision

I wasn't sure where to edit - is it the raw HTML or is there something like markdown to edit?

**Comment by PeteHaitch** [comment]
@kozo2 could you please make these changes

**Comment by kozo2** [comment]
@PeteHaitch Sorry for my late reply.
I updated https://biocasia2022.bioconductor.org/ like that.
Let me know again when the scholarship applications open.

**Comment by PeteHaitch** [comment]
Thank you, Kozo!

**Comment by PeteHaitch** [comment]
Scholarship applications are now open: https://forms.gle/8Fjzngv9pGYLQUaZ6
Could you please update the website @kozo2 
Thank you!

**Comment by kozo2** [comment]
@PeteHaitch I updated https://biocasia2022.bioconductor.org/.
(I added "Scholarship applications are now open: https://forms.gle/8Fjzngv9pGYLQUaZ6" to the website.)

**Comment by PeteHaitch** [comment]
Thank you!
